# Generated by Django 4.2.3 on 2023-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('full_name', models.CharField(max_length=70)),
                ('birhtdate', models.DateField()),
            ],
        ),
    ]
