# Generated by Django 4.2.3 on 2023-07-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('brand', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
